# file: k8-master/tasks/install-k8.yml
- name: Clone kubernetes
  git:
    repo: 'https://github.com/Project31/kubernetes-installer-rpi.git'
    dest: /srv/git/k8

- name: Changing perm of "/srv/git/k8/build-master.sh", adding "+x"
  file: dest=/srv/git/k8/build-master.sh mode=a+x

- name: Run kubernetes install script
  script: /srv/git/k8/build-master.sh